# Generated by Django 5.1.2 on 2024-10-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('development', 'Development'), ('review', 'Review'), ('completed', 'Completed')], default='development', max_length=32),
        ),
    ]
